language: c

services:
  - docker

script:
  - make docker-ci
  - docker cp mirage-xmpp-ci:/home/opam/app/pages/docs pages
  - docker cp mirage-xmpp-ci:/home/opam/app/pages/coverage pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: pages
