language: c
script:
  - bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE=mirage-xmpp
  matrix:
    - OCAML_VERSION=4.05

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: pages
