#!/usr/bin/env bash

# setup the network tunnel to allow communication
sudo ifconfig tap0 10.0.0.1 up

sleep 1
# send some simple data to the unikernel
# this should generate a warning in the unikernel logs due to bad document
echo "</error>" | nc -nw1 10.0.0.2 8080

# this should cause an unmatched end tag
echo "<start></a></start>" | nc -nw1 10.0.0.2 8080

# this should cause an unmatched start tag
echo "<start><a></start>" | nc -nw1 10.0.0.2 8080

# this should be accepted
echo "<stream></stream>" | nc -nw1 10.0.0.2 8080

# try sending some xmpp stanzas its way
echo "<stream>
<presence>
<show/>
</presence>
<message to='foo'>
<body>
hi
</body>
</message>
<iq to='bar' type='get'>
<query/>
</iq>
</stream>" | nc -nw1 10.0.0.2 8080

echo "<?xml version='1.0'?>
      <stream:stream
          from='juliet@im.example.com'
          to='im.example.com'
          version='1.0'
          xml:lang='en'
          xmlns='jabber:client'
          xmlns:stream='http://etherx.jabber.org/streams'>" | nc -nw1 10.0.0.2 8080

# printf "\n\nOpening a netcat connection\n"
# open a netcat session to the server
# nc 10.0.0.2 8080