(** The module for actions generated by the state machine *)

(** The type of actions, examples for now *)
type t =
  | SEND_STREAM_HEADER of {from : Jid.t; ato : Jid.t}
  | SEND_STREAM_FEATURES
  | REPLY_STANZA of Stanza.t
  | SERVER_GEN_RESOURCE_IDENTIFIER of string
  | CLOSE
  | ERROR of string
  | SET_JID of Jid.t
  | SET_JID_RESOURCE of string * string
  | GET_ROSTER of {from:Jid.t; id:string}
  | SET_ROSTER of string * Jid.t * Jid.t * string * string * string list
  | PUSH_ROSTER of Jid.t * Jid.t
  | ADD_TO_CONNECTIONS
  | REMOVE_FROM_CONNECTIONS

(** [to_string t] takes an action and returns its string representation *)
val to_string : t -> string
