(** The module for actions generated by the state machine *)

(** The type of actions, examples for now *)
type t =
  | REPLY_STANZA of bool * Stanza.t
  | SEND_STANZA of Jid.t * Stanza.t
  | CLOSE
  | ERROR of string
  | SET_JID of Jid.t
  | SET_JID_RESOURCE of string * string
  | GET_ROSTER of string * string

(** [to_string t] takes an action and returns its string representation *)
val to_string : t -> string
